Add support for stage failures in pipelines
mathworks/jenkins-matlab-plugin pull request #188
Opened 2021-04-22 13:32 UTC by abhargav-mw

This PR adds a new feature (xBug fix) for raising an exception if MATLAB process returned a non-zero exit code for Jenkins pipeline run. This adds a compatibility consideration as until now, plugin would set build result to failure incase MATLAB process returned non-zero exit code.

The behavior in case of MATLAB process being successful (that is returning 0 as exit code) stays the same.

2021-04-26 13:37 UTC, mcafaro approved these changes
:shipit:

2021-04-26 15:09 UTC, mw-hrastega requested changes

2021-04-26 15:09 UTC, mw-hrastega commented on src/main/resources/config.properties
> +matlab.execution.exception.prefix = Received non-zero exit code while trying to run MATLAB command (Exit code: %d)
Received a nonzero exit code %d while trying to run MATLAB.

We use "run MATLAB" in the doc. For example:
https://www.mathworks.com/help/matlab/matlab_env/run-matlab-from-azure-marketplace.html?searchHighlight=%22run%20matlab%22&s_tid=srchtitle

If you want MATLAB to be followed by something, you might consider "code" or "commands".

2021-04-26 15:14 UTC, nbhoski approved these changes
Ship it !

2021-04-27 13:54 UTC, mw-hrastega approved these changes

2021-04-27 15:27 UTC, jwpereira approved these changes
🚢

2021-04-27 15:41 UTC, merged