Run tests in parallel
mathworks/jenkins-matlab-plugin pull request #190
Opened 2021-05-11 20:24 UTC by BrianCian

Adding support for RunInParallel

2021-05-26 08:27 UTC, nbhoski requested changes

2021-05-26 08:27 UTC, nbhoski commented on src/main/java/com/mathworks/ci/RunMatlabTestsBuilder.java
> +        inputArgsList.add("'RunInParallel'" + "," + getRunTestsInParallel());
should we pass this to genscript if its not checked ?

2021-05-26 08:27 UTC, nbhoski commented on src/main/java/com/mathworks/ci/RunMatlabTestsStep.java
> +                inputArgs.add("'" + key + "'" + "," + Boolean.parseBoolean(val));
when this will be null ? since its boolean

2021-05-26 08:27 UTC, nbhoski commented on src/main/java/com/mathworks/ci/RunMatlabTestsStep.java
> +        args.put("RunInParallel", getRunTestsInParallel());
does it directly store boolean value in <String,string> type map ? did you consider String.valueOf() instead.

2021-05-26 08:27 UTC, nbhoski commented on src/main/java/com/mathworks/ci/RunMatlabTestsStep.java
> +                inputArgs.add("'" + key + "'" + "," + Boolean.parseBoolean(val));
Aah i see its string . But does it make sense to pass string value here ? i can still pass 'ABC'  which will return false . I dont have strong flag on this though

2021-05-26 08:27 UTC, nbhoski commented on src/main/java/com/mathworks/ci/RunMatlabTestsStep.java
> +        args.put("RunInParallel", getRunTestsInParallel());
Same as above

2021-05-26 08:27 UTC, nbhoski commented on src/main/resources/com/mathworks/ci/RunMatlabTestsBuilder/config.jelly
>  </f:block>
Corresponding Help files are still misiing

2021-05-26 08:27 UTC, nbhoski commented on src/main/resources/com/mathworks/ci/RunMatlabTestsStep/config.jelly
>  	</f:entry>
Corresponding help files are still missing

2021-05-26 08:31 UTC, nbhoski commented
Also , These changes require doc update. make sure we have corresponding changes either in same PR or separate PR and is approved.

2021-07-09 15:07 UTC, BrianCian commented
Ran into an issue with getting this to work with Artifacts. Also was having trouble getting help to work the 'checkbox'. Closing for now as I will be working on another project, but will come back to this at a later date.

2021-07-09 15:07 UTC, closed without merging