2.8.1 snapshot qualification
mathworks/jenkins-matlab-plugin pull request #217
Opened 2022-06-28 05:03 UTC by dolonm-mw

This PR closes #215 
Details:

1. New strategy to unzip MATLAB Scriptgen package to avoid being picked up by MATLAB Code Coverage tool
2. Supports both regular remote agents and container-based agents.
3. Earlier strategy- unzipping scriptgen inside .matlab folder in workspace.
4. New strategy-copy the scriptgen zip folder to system-specific temporary folder and unzip it here.
5. No helper files in the workspace.

2022-07-14 10:30 UTC, Vahila requested changes
In the new unzipping strategy, '.matlab' folder still contains the runner script which could affect the code coverage if not deleted.

2022-08-30 07:27 UTC, Vahila commented
Qualification checks made:

- Code coverage report is generated correctly.
- Docker workflow does not have any issues.
- No issues with backwards compatibility.

2022-08-30 07:27 UTC, Vahila approved these changes

2022-08-30 08:17 UTC, nbhoski commented
Merging unzipping strategy changes

2022-08-30 08:18 UTC, merged